export type Category = "Refrigeration" | "Heating" | "Stainless, Processing and Others";

export type Product = {
  id: string;
  name: string;
  model: string;
  category: Category;
  image: string;
};

export const categories: Category[] = [
  "Refrigeration",
  "Heating",
  "Stainless, Processing and Others",
];

export const categorySlugs: Record<Category, string> = {
  "Refrigeration": "refrigeration",
  "Heating": "heating",
  "Stainless, Processing and Others": "stainless-processing-others",
};

export const products: Product[] = [
  { id: "108", name: "Showcase Fridge", model: "TE-108", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/Banco_GRANADA_per_alimenti_semi-statico_prof._955_.jpg" },
  { id: "106", name: "Showcase Fridge", model: "TE-106", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/af-copia1.jpg" },
  { id: "109", name: "Showcase Fridge", model: "TE-109", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/banco_frigorifero_3.jpg" },
  { id: "102", name: "Showcase Fridge", model: "TE-102", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/big_SLUX_WHITE_1.jpg" },
  { id: "104", name: "Ice Cream Display", model: "TE-104", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/Evo_350.jpg" },
  { id: "110", name: "Showcase Cake Fridge", model: "TE-110", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/cake_ref.jpg" },
  { id: "105", name: "Cake Fridge", model: "TE-105", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/CAKE_REF.jpg" },
  { id: "134", name: "Showcase Fridge", model: "TE-134", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/cake-display-counter-500x500.jpg" },
  { id: "135", name: "Showcase Fridge", model: "TE-135", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/cake_fridge.jpg" },
  { id: "137", name: "Showcase Fridge", model: "TE-137", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/CD10BON900CD.jpg" },
  { id: "144", name: "Showcase Fridge", model: "TE-144", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/shocase-fridge-144.jpg" },
  { id: "143", name: "Showcase Fridge", model: "TE-143", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/shocase-fridge-143.jpg" },
  { id: "149", name: "Showcase", model: "TE-149", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/showcase-149.jpg" },
  { id: "111", name: "Showcase Fridge", model: "TE-111", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/showcase-fridge-111.jpg" },
  { id: "146", name: "Showcase Fridge", model: "TE-146", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/showcase-fridge-146.jpg" },
  { id: "113", name: "Open Chiller", model: "TE-113", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/open-chiller-113.jpg" },
  { id: "141", name: "Open Chiller", model: "TE-141", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/open-chiller-141.jpg" },
  { id: "142", name: "Open Chiller", model: "TE-142", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/open-chiller-142.jpg" },
  { id: "150", name: "Showcase", model: "TE-150", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/showcase-150.jpg" },
  { id: "151", name: "Showcase", model: "TE-151", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/showcase-151.jpg" },
  { id: "114", name: "Meat Fridge", model: "TE-114", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/meat-fridge-114.jpg" },
  { id: "117", name: "Cabinet Fridge", model: "TE-117", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/cabinet-fridge-117.jpg" },
  { id: "119", name: "Meat Fridge", model: "TE-119", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/meat-fridge-119.jpg" },
  { id: "145", name: "Upright Fridge", model: "TE-145", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/upright-fridge-145.jpg" },
  { id: "126", name: "Upright Fridge", model: "TE-126", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/upright-fridge-126.jpg" },
  { id: "127", name: "Upright Fridge", model: "TE-127", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/upright-fridge-127.jpg" },
  { id: "139", name: "Upright Fridge", model: "TE-139", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/w222020000.jpg" },
  { id: "120", name: "One Door Fridge", model: "TE-120", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/one-door-fridge-120.jpg" },
  { id: "121", name: "Cheese Fridge", model: "TE-121", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/cheese-fridge-121.jpg" },
  { id: "122", name: "Sliding Doors Fridge", model: "TE-122", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/sliding-doors-fridge-122.jpg" },
  { id: "123", name: "Sliding Doors Fridge", model: "TE-123", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/sliding-doors-fridge-123.jpg" },
  { id: "124", name: "Cheese Fridge", model: "TE-124", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/cheest-fridge-1241.jpg" },
  { id: "116", name: "Table Fridge", model: "TE-116", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/table_fridge.jpg" },
  { id: "140", name: "Table Fridge", model: "TE-140", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/table-fridge-140.jpg" },
  { id: "147", name: "Showcase Fridge", model: "TE-147", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/showcase-fridge-147.jpg" },
  { id: "115", name: "Beverage Bar", model: "TE-115", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/beverage-bar-115.jpg" },
  { id: "148", name: "Cold Room", model: "TE-148", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/cold-room-148.jpg" },
  { id: "131", name: "Ice Maker", model: "TE-131", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/ice-maker-131.jpg" },
  { id: "132", name: "Morgue Fridge, Two Body", model: "TE-132", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/two_body_mobile_refrigerator.jpg" },
  { id: "133", name: "Morgue Fridge, One Body", model: "TE-133", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/morgue-fridge-one-body-133.jpg" },
  { id: "103", name: "Salad Bar", model: "TE-103", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/_H9T8328_MOD_727x335_01_72dpi_1.jpg" },
  { id: "107", name: "Showcase Fridge", model: "TE-107", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/showcase-fridge-107.jpg" },
  { id: "125", name: "Counter Fridge", model: "TE-125", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/self800-big.jpg" },
  { id: "128", name: "Pizza Fridge", model: "TE-128", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/_H9T9169_727x335_3.jpg" },
  { id: "129", name: "Water Tank", model: "TE-129", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/category1332774363.jpg" },
  { id: "218", name: "Slush Machine", model: "TE-218", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/s-l300.jpg" },
  { id: "219", name: "Cold Drink Dispenser", model: "TE-219", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/cold-drink-dispenser-219.jpg" },
  { id: "224", name: "Ice Cream Machine", model: "TE-224", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/20120105174802040.jpg" },
  { id: "130", name: "Hard Cream Fridge", model: "TE-130", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/ice_cream_fridge.png" },
  { id: "136", name: "Upright Fridge", model: "TE-136", category: "Refrigeration", image: "https://traboulsiest.com/uploads/products/600x455/up_right_fridge.jpg" },
  { id: "155", name: "Gas Cookers", model: "TE-155", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/aer-6-36-backsplash_low.jpg" },
  { id: "186", name: "Gas Stove With Oven", model: "TE-186", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/aer-4-24_low.jpg" },
  { id: "182", name: "Gas Stove (Single Burner)", model: "TE-182", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/download_(12).jpg" },
  { id: "184", name: "Gas Stove", model: "TE-184", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/images_(1" },
  { id: "185", name: "Gas Lava Rock Grill", model: "TE-185", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/aerb-36.jpg" },
  { id: "172", name: "Charcoal Grill", model: "TE-172", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/aerb-12.jpg" },
  { id: "183", name: "Gas Griddle", model: "TE-183", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/aemg-36_low.jpg" },
  { id: "180", name: "Gas Griddle", model: "TE-180", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/aemg-24_lowii.jpg" },
  { id: "174", name: "Plate Cooker", model: "TE-174", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/plate-cooker-174.jpg" },
  { id: "179", name: "Complete Set", model: "TE-179", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/complete-set-179.jpg" },
  { id: "153", name: "Single Pizza Oven", model: "TE-153", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/images_(69" },
  { id: "152", name: "Double Pizza Oven", model: "TE-152", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/TT-O75.jpg" },
  { id: "157", name: "Convection Oven", model: "TE-157", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/56216-9455597.jpg" },
  { id: "188", name: "Salamander", model: "TE-188", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/salamander-188.jpg" },
  { id: "190", name: "Salamander", model: "TE-190", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/salamander-190.jpg" },
  { id: "158", name: "Hot Showcase", model: "TE-158", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/hot-showcase-158.jpg" },
  { id: "177", name: "Fryer, One Basket", model: "TE-177", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/aef-_3540_s_low.jpg" },
  { id: "167", name: "Broasted Machine", model: "TE-167", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/broasted_machine.png" },
  { id: "154", name: "Hood", model: "TE-154", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/hood_st.jpg" },
  { id: "159", name: "Gas Grill 14 Spits", model: "TE-159", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/images_(1" },
  { id: "161", name: "Shawarma Grill Double", model: "TE-161", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/shawarma-grill-double-161.jpg" },
  { id: "173", name: "Shawarma Grill", model: "TE-173", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/shawarma-grill-173.jpg" },
  { id: "187", name: "Hot Dog Roller", model: "TE-187", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/hotdogroller.jpg" },
  { id: "189", name: "Contact Grill Double", model: "TE-189", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/contact_grill_double.jpg" },
  { id: "191", name: "Contact Grill", model: "TE-191", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/contact_grill_1.jpg" },
  { id: "192", name: "Waffle Machine", model: "TE-192", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/weefer_machine.jpg" },
  { id: "193", name: "Crepe Machine", model: "TE-193", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/crepe_machine.jpg" },
  { id: "194", name: "Hot Dog Warmer", model: "TE-194", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/hot-dog-warmer-194.jpg" },
  { id: "195", name: "Work Table", model: "TE-195", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images1.jpg" },
  { id: "196", name: "Sinks", model: "TE-196", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images_(3" },
  { id: "198", name: "Work Table", model: "TE-198", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/Thunder-Group-SLWT43072F4-Stainless-Steel-Work-Table--30--x-72--x-34-255010_thumb.jpg" },
  { id: "199", name: "Sinks", model: "TE-199", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/download.jpg" },
  { id: "201", name: "Cupboard", model: "TE-201", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/cupboard-201.jpg" },
  { id: "213", name: "Steel Service Cart", model: "TE-213", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/OEM-or-ODM-Stainless-Steel-Work-Table-Food-Working-Stand.jpg" },
  { id: "214", name: "Steel Service Cart", model: "TE-214", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/67911-9015084.jpg" },
  { id: "203", name: "Sinks", model: "TE-203", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/download_(1" },
  { id: "205", name: "Steel Shelves", model: "TE-205", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images_(2" },
  { id: "235", name: "Serving Cart", model: "TE-235", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/serving-cart-235.jpg" },
  { id: "206", name: "Cupboard", model: "TE-206", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images_(19" },
  { id: "207", name: "Cupboard", model: "TE-207", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/cupboard-207.jpg" },
  { id: "208", name: "Cupboard", model: "TE-208", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/cupboard-208.jpg" },
  { id: "209", name: "Cupboard", model: "TE-209", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/cupboard-209.jpg" },
  { id: "210", name: "Steel Service Cart", model: "TE-210", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steel-service-cart-210.jpg" },
  { id: "211", name: "Steel Service Cart", model: "TE-211", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steel-service-cart-211.jpg" },
  { id: "212", name: "Steel Service Cart", model: "TE-212", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steel-service-cart-212.jpg" },
  { id: "216", name: "Dish Washer", model: "TE-216", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/dish-washer-216.jpg" },
  { id: "1", name: "Set", model: "TE-1", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/set-1.jpg" },
  { id: "2", name: "Set", model: "TE-2", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/set-3.jpg" },
  { id: "220", name: "Carrot Juicer", model: "TE-220", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/download_(2" },
  { id: "222", name: "Electric Orange Juicer", model: "TE-222", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images_(1" },
  { id: "232", name: "Vegetable Cutter Machine", model: "TE-232", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/vegetable-cutter-machine-232.jpg" },
  { id: "256", name: "Espresso Machine", model: "TE-256", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images_(17" },
  { id: "236", name: "Milk Shaker", model: "TE-236", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/milk-shaker-236.jpg" },
  { id: "226", name: "Hummus Machine 6L", model: "TE-226", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/hommse-machine-6l-226.jpg" },
  { id: "228", name: "Hummus Machine 12L", model: "TE-228", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/hommse-machine-12l-228.jpg" },
  { id: "225", name: "Planetary Mixer", model: "TE-225", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/planetary-mixer-10lt.jpg" },
  { id: "227", name: "Hand Impulse Sealer", model: "TE-227", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/hand-impulse-sealer-227.jpg" },
  { id: "229", name: "Can Opener", model: "TE-229", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/can-opener-229.jpg" },
  { id: "165", name: "Dough Sheeter", model: "TE-165", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/DOUGH_SHEETER.jpg" },
  { id: "166", name: "Dough Maker", model: "TE-166", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/pic10.jpg" },
  { id: "230", name: "Complete Set", model: "TE-230", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/complete-set-230.jpg" },
  { id: "231", name: "Manual Hamburger Press", model: "TE-231", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/manual_hamberger_machine.jpg" },
  { id: "250", name: "Meat Slicer", model: "TE-250", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images_(32" },
  { id: "164", name: "Cutter Machine", model: "TE-164", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/cutter-machine-164.jpg" },
  { id: "251", name: "Steak Machine", model: "TE-251", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steak-machine-251.jpg" },
  { id: "252", name: "Bone Sawer", model: "TE-252", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/bone-sawer-252.png" },
  { id: "253", name: "Meat Mincer", model: "TE-253", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/Meat_mincer_sap.jpg" },
  { id: "254", name: "Kibbeh Machine", model: "TE-254", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/kebbeh-machine-254.jpg" },
  { id: "255", name: "Electric Meat Mincer", model: "TE-255", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/electric-meat-mincer-255.jpg" },
  { id: "257", name: "Potato Peeler", model: "TE-257", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/potato-peeler-257.jpg" },
  { id: "234", name: "Dish Warmer", model: "TE-234", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/plate-warmer.jpg" },
  { id: "237", name: "Pizza Roller", model: "TE-237", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/pizza_roller.jpg" },
  { id: "238", name: "Toast Slicer", model: "TE-238", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/toast-slicer-238.jpg" },
  { id: "239", name: "Croissant Sheeter", model: "TE-239", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/croissant-cheeter-239.jpg" },
  { id: "240", name: "Auto Pedal Sealer", model: "TE-240", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/Impulse_sealer_machine.jpg" },
  { id: "242", name: "Impulse Sealing Machine", model: "TE-242", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/Impulse_sealer.jpg" },
  { id: "243", name: "Insect Killer", model: "TE-243", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/insect-killer-243.jpg" },
  { id: "244", name: "Vacuum Packer", model: "TE-244", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/vaccum_machine.jpg" },
  { id: "249", name: "Sausage Filler", model: "TE-249", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/TT-F89A.jpg" },
  { id: "258", name: "Needle Scale", model: "TE-258", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/needle-scale-258.jpg" },
  { id: "259", name: "Electric Scale", model: "TE-259", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/electric-scale-259.jpg" },
  { id: "260", name: "Electric Scale", model: "TE-260", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/electric-scale.png" },
  { id: "223", name: "Popcorn Machine", model: "TE-223", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/images_(35" },
  { id: "233", name: "Candy Machine", model: "TE-233", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/candy-machine-233.png" },
  { id: "163", name: "Lahme Ajeen Oven", model: "TE-163", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/images.jpg" },
  { id: "168", name: "Steel BBQ", model: "TE-168", category: "Heating", image: "https://traboulsiest.com/uploads/products/600x455/steel-bbq-168.jpg" },
  { id: "245", name: "Market Cart", model: "TE-245", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/market-cart-245.jpg" },
  { id: "247", name: "Storage Shelves", model: "TE-247", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/storage-shelves-247.jpg" },
  { id: "248", name: "Storage Shelves", model: "TE-248", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/storage-shelves-2481.jpg" },
  { id: "262", name: "Steel Pans", model: "TE-262", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steel-pans-262.jpg" },
  { id: "263", name: "Steel and Glass Products", model: "TE-263", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steel-and-glass-products-263.jpg" },
  { id: "264", name: "Polycarbonate Storage Pans", model: "TE-264", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/polycarbonate-storage-pans-264.jpg" },
  { id: "265", name: "Steel Pans", model: "TE-265", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steel-pans-265.jpg" },
  { id: "266", name: "Steel Pans", model: "TE-266", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/steel-pans-266.jpg" },
  { id: "270", name: "Knives", model: "TE-270", category: "Stainless, Processing and Others", image: "https://traboulsiest.com/uploads/products/600x455/knifes-270.jpg" },
];