export const siteConfig = {
  name: "Traboulsi Est.",
  fullName: "Traboulsi Est. for Trading & Industry",
  tagline: "Commercial Kitchen Equipment for Restaurants, Hotels, Hospitals & Supermarkets",
  phone: "+961 7 530 986",
  phoneHref: "tel:+9617530986",
  mobile: "+961 3 829 906",
  mobileHref: "tel:+9613829906",
  fax: "+961 7 530 986",
  faxHref: "tel:+9617530986",
  email: "info@traboulsiest.com",
  address: "Deir el Zahrani, Nabatieh, Lebanon",
  mapsLink: "https://maps.app.goo.gl/ckmX7kDXxTYcbRuP8",
  facebook: "https://www.facebook.com/traboulsi.est",
  mapsEmbed: "https://maps.google.com/maps?q=33.4338035,35.4443397&z=17&output=embed",
  logo: "/logo.png",
  capabilitiesBanner: "/capabilities-banner.png",
  heroImages: [
    "/images/hero/trab.jpg",
    "/images/hero/trab2.jpg",
    "/images/hero/trab3.jpg",
  ],
  aboutImage: "/images/about/tra1.jpg",
  founded: 1982,
};
